/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dav(props) {
  const { nodes, materials } = useGLTF("/5D PEDRO VICENTE.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.14, 0]} rotation={[0, -1.57, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq2_ARD-geom002"].geometry}
          material={materials["tq2_ARD_front.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq2_ARD-geom002_1"].geometry}
          material={materials["tq2_ARD_back.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["tq2_ARD-geom002_2"].geometry}
          material={materials["tq2_ARD_edge.002"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/5D PEDRO VICENTE.gltf");
